title: Hannes Diercks
email: hi@xiphe.net
description: >
  Web developer and advisor, love tooling/automation, know how to agile,
  strive to improve work culture, servers are so 2010, ambassador of pattern-thinking,
  have a design background, pretty good musician
baseurl: ""
url: "https://xiphe.net"
twitter_username: XipheHH
github_username: Xiphe
twitter:
  username: XipheHH
  card: summary_large_image

social:
  name: Hannes Diercks
  links:
    - https://twitter.com/XipheHH
    - https://github.com/Xiphe
    - https://www.xing.com/profile/Hannes_Diercks/

# Build settings
markdown: kramdown
theme: minima

plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
